import type { StencilColor } from "./lib/stencil";

/** ステンシル印刷で実際に使われる代表的なインクカラー */
export const INKS = {
  white: { name: "White", color: "#FFFFFF" },
  black: { name: "Black", color: "#000000" },
  burgundy: { name: "Burgundy", color: "#914E72" },
  blue: { name: "Blue", color: "#0078BF" },
  green: { name: "Green", color: "#00A95C" },
  mediumBlue: { name: "Medium Blue", color: "#3255A4" },
  brightRed: { name: "Bright Red", color: "#F15060" },
  federalBlue: { name: "Federal Blue", color: "#3D5588" },
  purple: { name: "Purple", color: "#765BA7" },
  teal: { name: "Teal", color: "#00838A" },
  gold: { name: "Gold", color: "#CFB53B" },
  silver: { name: "Silver", color: "#C0C0C0" },
  bronze: { name: "Bronze", color: "#CD7F32" },
  flatGold: { name: "Flat Gold", color: "#BB8B41" },
  hunterGreen: { name: "Hunter Green", color: "#407060" },
  red: { name: "Red", color: "#FF665E" },
  orange: { name: "Orange", color: "#FF6C2F" },
  yellow: { name: "Yellow", color: "#FFE800" },
  fluorescentPink: { name: "Fluorescent Pink", color: "#FF48B0" },
  fluorescentOrange: { name: "Fluorescent Orange", color: "#FF7477" },
  cornflower: { name: "Cornflower", color: "#62A8E5" },
  skyBlue: { name: "Sky Blue", color: "#4982CF" },
  seaBlue: { name: "Sea Blue", color: "#0074A2" },
  lake: { name: "Lake", color: "#235BA8" },
  indigo: { name: "Indigo", color: "#484D7A" },
  midnight: { name: "Midnight", color: "#435060" },
  mist: { name: "Mist", color: "#D5E4C0" },
  granite: { name: "Granite", color: "#A5AAA8" },
  charcoal: { name: "Charcoal", color: "#70747C" },
  smoky: { name: "Smoky Teal", color: "#5F8289" },
  steel: { name: "Steel", color: "#375E77" },
  slate: { name: "Slate", color: "#5E695E" },
  turquoise: { name: "Turquoise", color: "#00AA93" },
  emerald: { name: "Emerald", color: "#19975D" },
  grass: { name: "Grass", color: "#397E58" },
  forest: { name: "Forest", color: "#516E5A" },
  spruce: { name: "Spruce", color: "#4A635D" },
  moss: { name: "Moss", color: "#68724D" },
  seaFoam: { name: "Sea Foam", color: "#62C2B1" },
  kelly: { name: "Kelly Green", color: "#67B346" },
  light_lime: { name: "Light Lime", color: "#E3ED55" },
  brick: { name: "Brick", color: "#A75154" },
  mahogany: { name: "Mahogany", color: "#8E595A" },
  wine: { name: "Wine", color: "#914E72" },
  lipstick: { name: "Lipstick", color: "#BA4D68" },
  cranberry: { name: "Cranberry", color: "#D14070" },
  bubble_gum: { name: "Bubble Gum", color: "#F984CA" },
  lightMauve: { name: "Light Mauve", color: "#E6B5C9" },
  dark_mauve: { name: "Dark Mauve", color: "#BD8CA6" },
  violet: { name: "Violet", color: "#9D7AD2" },
  orchid: { name: "Orchid", color: "#AA60BF" },
  plum: { name: "Plum", color: "#845991" },
  raisin: { name: "Raisin", color: "#775D7A" },
  grape: { name: "Grape", color: "#6C5D80" },
  scarlet: { name: "Scarlet", color: "#FF585E" },
  tomato: { name: "Tomato", color: "#D2515E" },
  cranberry2: { name: "Cranberry", color: "#D14070" },
  maroon: { name: "Maroon", color: "#9E4C6E" },
  raspberry: { name: "Raspberry", color: "#D1517A" },
  paprika: { name: "Paprika", color: "#EE5D31" },
  pumpkin: { name: "Pumpkin", color: "#FF6F31" },
  brightOlive: { name: "Bright Olive", color: "#B49F29" },
  brightGold: { name: "Bright Gold", color: "#BA8032" },
  copper: { name: "Copper", color: "#BD6439" },
  mahogany2: { name: "Mahogany", color: "#8E595A" },
  bisque: { name: "Bisque", color: "#F2CDCF" },
  peach: { name: "Peach", color: "#FF9E6C" },
  salmon: { name: "Salmon", color: "#FF8F8F" },
  lightTeal: { name: "Light Teal", color: "#009DA5" },
  warmRed: { name: "Warm Red", color: "#FF4C65" },
  fluorescentGreen: { name: "Fl. Green", color: "#44D62C" },
  fluorescentBlue: { name: "Fl. Blue", color: "#4FDBF0" },
  fluorescentYellow: { name: "Fl. Yellow", color: "#FFE916" },
} as const satisfies Record<string, StencilColor>;

/** 代表的な色の組み合わせプリセット */
export const PRESETS = {
  classic: {
    name: "Classic (Blue + Red)",
    colors: [INKS.blue, INKS.brightRed],
  },
  retro: {
    name: "Retro (Teal + Orange)",
    colors: [INKS.teal, INKS.orange],
  },
  neon: {
    name: "Neon (Fl. Pink + Fl. Green)",
    colors: [INKS.fluorescentPink, INKS.fluorescentGreen],
  },
  tricolor: {
    name: "Tricolor (Blue + Red + Yellow)",
    colors: [INKS.blue, INKS.brightRed, INKS.yellow],
  },
  cmyk: {
    name: "CMYK-like (Blue + Red + Yellow + Black)",
    colors: [
      INKS.blue,
      INKS.brightRed,
      INKS.yellow,
      INKS.black,
    ],
  },
  botanical: {
    name: "Botanical (Green + Burgundy)",
    colors: [INKS.green, INKS.burgundy],
  },
  midnight: {
    name: "Midnight (Midnight + Violet + Fl. Pink)",
    colors: [INKS.midnight, INKS.violet, INKS.fluorescentPink],
  },
  fluorescent: {
    name: "Fluorescent (Fl. Blue + Fl. Pink + Fl. Yellow)",
    colors: [
      INKS.fluorescentBlue,
      INKS.fluorescentPink,
      INKS.fluorescentYellow,
    ],
  },
} as const satisfies Record<
  string,
  { name: string; colors: readonly StencilColor[] }
>;
